# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI DEV

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16.x, 18.x, 20.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        ref: "develop"
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
    # prerelease --preid=ci-$GITHUB_RUN_ID
    - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
    - run: npm run build
    - run: npm pack
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: "*.tgz"

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
        - name: Upload
          uses: actions/download-artifact@v3
          with:
              name: package
        - uses: actions/setup-node@v3
          with:
            node-version: 18.x
            registry-url: https://npm.pkg.github.com/
            scope: "@abstractplay"
        - run: echo "registry=https://npm.pkg.github.com/@abstractplay" >> .npmrc
        - run: npm publish $(ls *.tgz) --tag development
          env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  relay:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger gameslib build and test
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_WORKFLOWS }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/abstractplay/gameslib/dispatches \
          -d '{"event_type": "dep_update_dev"}'

      - name: Trigger designer rebuild
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_WORKFLOWS }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/abstractplay/designer/dispatches \
          -d '{"event_type": "dep_update_prod"}'

